/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendadevideo;

/**
 *
 * @author salasistemas
 */

import java.sql.Connection;
import java.sql.Statement;
public class Menu extends javax.swing.JFrame {
     Connection con=null;
     Statement stmt=null; 
    /**
     * Creates new form Menu
     */
    public Menu(Connection con,Statement stmt ) {
        this.con=con;
        this.stmt=stmt;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuActor = new javax.swing.JMenuItem();
        menuPelicula = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("ARCHIVO");

        menuActor.setText("Actor");
        menuActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActorActionPerformed(evt);
            }
        });
        jMenu1.add(menuActor);

        menuPelicula.setText("Pelicula");
        menuPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPelicula);

        menuUsuario.setText("Usuario");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuario);

        menuCategoria.setText("Categoria");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCategoria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("EDICIÓN");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("CONSULTAR");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("REPORTES");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("AYUDA");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActorActionPerformed
        Actor objAct = new Actor();
        objAct.setVisible(true);
    }//GEN-LAST:event_menuActorActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
       Usuario objUsu = new Usuario();
       objUsu.setVisible(true);
       
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPeliculaActionPerformed
       Pelicula objPel = new Pelicula();
       objPel.setVisible(true);;
    }//GEN-LAST:event_menuPeliculaActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
         Categoria objCat = new Categoria();
        objCat.setVisible(true);;
    }//GEN-LAST:event_menuCategoriaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuActor;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuPelicula;
    private javax.swing.JMenuItem menuUsuario;
    // End of variables declaration//GEN-END:variables
}
